services:
  didit-api:
    image: ghcr.io/ddiddit/didit-backend:latest
    container_name: didit-api
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      FLYWAY_REPAIR: ${FLYWAY_REPAIR}
    networks:
      - didit-network
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /home/didit-dev/didit/firebase:/home/didit-dev/didit/firebase

networks:
  didit-network:
    external: true