spring:
  docker:
    compose:
      enabled: true
      lifecycle-management: start_only

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    open-in-view: false

  flyway:
    enabled: false

firebase:
  service-account-path: src/main/resources/firebase/firebase-service-account.json

jwt:
  secret: /jc2w58FPaFaRr9aOAudmWLTlf8rgeD6e5pKU2Hz3Dw=