spring:
  docker:
    compose:
      enabled: true
      lifecycle-management: start_only

  jpa:
    show-sql: true
    open-in-view: false

firebase:
  service-account-path: src/main/resources/firebase/firebase-service-account.json