{
 "title": "Didit - Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\r\n  process_uptime_seconds{\r\n    job=\"didit-api\"\r\n  }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(\r\n    jvm_memory_used_bytes{\r\n      area=\"heap\",\r\n      job=\"didit-api\"\r\n    }\r\n  )\r\n  /\r\n  sum(\r\n    jvm_memory_max_bytes{\r\n      area=\"heap\",\r\n      job=\"didit-api\"\r\n    }\r\n  )\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Non-Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(\r\n    jvm_memory_used_bytes{\r\n      area=\"nonheap\",\r\n      job=\"didit-api\"\r\n    }\r\n  )\r\n  /\r\n  sum(\r\n    jvm_memory_max_bytes{\r\n      area=\"nonheap\",\r\n      job=\"didit-api\"\r\n    }\r\n  )\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\r\n  avg(\r\n    rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\r\n  ) * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Server Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  1 -\r\n  (\r\n    node_memory_MemAvailable_bytes\r\n    /\r\n    node_memory_MemTotal_bytes\r\n  )\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  1 -\r\n  node_filesystem_avail_bytes{\r\n    mountpoint=\"/\",\r\n    fstype!=\"tmpfs\"\r\n  }\r\n  /\r\n  node_filesystem_size_bytes{\r\n    mountpoint=\"/\",\r\n    fstype!=\"tmpfs\"\r\n  }\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM Statistics - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "JVM Memory pools",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{\r\n  id=\"G1 Eden Space\",\r\n  job=\"didit-api\"\r\n}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_used_bytes{\r\n  id=\"G1 Old Gen\",\r\n  job=\"didit-api\"\r\n}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_used_bytes{\r\n  id=\"G1 Survivor Space\",\r\n  job=\"didit-api\"\r\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM Statistics - GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "JVM GC Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{job=\"didit-api\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{job=\"didit-api\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HikariCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "HikariCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{job=\"didit-api\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hikaricp_connections_idle{job=\"didit-api\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hikaricp_connections_pending{job=\"didit-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HikariCP Acquire Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(\r\n  hikaricp_connections_acquire_seconds_sum{\r\n    job=\"didit-api\"\r\n  }[5m]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"didit-api\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate By Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"didit-api\"}[5m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API p95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(\r\n    rate(\r\n      http_server_requests_seconds_bucket{\r\n        job=\"didit-api\"\r\n      }[5m]\r\n    )\r\n  ) by (le)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Error Rate",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    http_server_requests_seconds_count{\r\n      job=\"didit-api\",\r\n      status=~\"5..\"\r\n    }[5m]\r\n  )\r\n) or vector(0)\r\n/\r\nsum(\r\n  rate(\r\n    http_server_requests_seconds_count{\r\n      job=\"didit-api\"\r\n    }[5m]\r\n  )\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow APIs (p95)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(\r\n  5,\r\n  histogram_quantile(\r\n    0.95,\r\n    sum(\r\n      rate(\r\n        http_server_requests_seconds_bucket{\r\n          job=\"didit-api\"\r\n        }[5m]\r\n      )\r\n    ) by (le, uri)\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 API Requests",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(\r\n  5,\r\n  sum(\r\n    rate(\r\n      http_server_requests_seconds_count{\r\n        job=\"didit-api\"\r\n      }[5m]\r\n    )\r\n  ) by (uri)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Log Level Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    logback_events_total[5m]\r\n  )\r\n) by (level)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}