{
 "title": "Didit - Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ERROR Count (5m)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  count_over_time(\r\n    {container=~\"didit-api-.*\"} |= \"ERROR\" [5m]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Log Rate by Container",
   "type": "timeseries",
   "description": "Container log rate by container",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum by(container)(\r\n  rate({source=\"docker\"}[1m])\r\n)"
    }
   ]
  },
  {
   "title": "Recent ERROR Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{container=~\"didit-api-.*\"} |= \"ERROR\""
    }
   ]
  },
  {
   "title": "Recent Exception Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{container=~\"didit-api-.*\"} |= \"Exception\""
    }
   ]
  },
  {
   "title": "Recent WARN Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{container=~\"didit-api-.*\"} |= \"WARN\""
    }
   ]
  }
 ]
}