events {}

http {
    include /etc/nginx/conf.d/upstream-didit.conf;

    server {
        listen 80;
        server_name api.didit.ai.kr;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name api.didit.ai.kr;

        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        location / {
            proxy_pass http://didit-api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
