apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord-critical
    receivers:
      - uid: discord-critical
        type: discord
        disableResolveMessage: false
        settings:
          url: $DISCORD_ALERT_CRITICAL_WEBHOOK_URL
          use_discord_username: false

  - orgId: 1
    name: discord-warning
    receivers:
      - uid: discord-warning
        type: discord
        disableResolveMessage: false
        settings:
          url: $DISCORD_ALERT_WARNING_WEBHOOK_URL
          use_discord_username: false