apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord-monitor-critical
    receivers:
      - uid: discord-monitor-critical
        type: discord
        disableResolveMessage: false
        settings:
          url: $DISCORD_MONITOR_WEBHOOK_URL
          use_discord_username: false
