apiVersion: 1

policies:
  - orgId: 1
    receiver: discord-warning
    group_by:
      - grafana_folder
      - alertname
      - severity
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: discord-critical
        object_matchers:
          - [ 'severity', '=', 'critical' ]
        continue: false

      - receiver: discord-warning
        object_matchers:
          - [ 'severity', '=', 'warning' ]
        continue: false