apiVersion: 1

groups:
  - orgId: 1
    name: didit-prod-critical
    folder: Didit Alerts
    interval: 1m
    rules:
      - uid: didit-jvm-heap-usage-critical
        title: '[CRITICAL] JVM Heap 메모리 사용률 85% 초과'
        condition: C
        data:
          - refId: A
            datasourceUid: prometheus
            relativeTimeRange:
              from: 300
              to: 0
            model:
              refId: A
              expr: |
                sum(jvm_memory_used_bytes{environment="prod", area="heap"})
                /
                sum(jvm_memory_max_bytes{environment="prod", area="heap"})
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200

          - refId: B
            datasourceUid: __expr__
            model:
              refId: B
              type: reduce
              expression: A
              reducer: last
              datasource:
                type: __expr__
                uid: __expr__

          - refId: C
            datasourceUid: __expr__
            model:
              refId: C
              type: threshold
              expression: B
              conditions:
                - evaluator:
                    type: gt
                    params: [ 0.85 ]
                  operator:
                    type: and
                  query:
                    params: [ C ]
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__

        noDataState: OK
        execErrState: Alerting
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: JVM heap 메모리 사용률이 85%를 초과했습니다
          description: |
            - JVM Heap 및 GC 상태
            - 최근 트래픽 증가 여부
            - 메모리 누수 및 OOM 로그

      - uid: didit-http-5xx-detected
        title: '[CRITICAL] 5xx 에러 발생'
        condition: C
        data:
          - refId: A
            datasourceUid: prometheus
            relativeTimeRange:
              from: 120
              to: 0
            model:
              refId: A
              expr: |
                sum(
                  increase(
                    http_server_requests_seconds_count{
                      environment="prod",
                      status=~"5.."
                    }[1m]
                  )
                )
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200

          - refId: B
            datasourceUid: __expr__
            model:
              refId: B
              type: reduce
              expression: A
              reducer: last
              datasource:
                type: __expr__
                uid: __expr__

          - refId: C
            datasourceUid: __expr__
            model:
              refId: C
              type: threshold
              expression: B
              conditions:
                - evaluator:
                    type: gt
                    params: [ 0 ]
                  operator:
                    type: and
                  query:
                    params: [ C ]
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__

        noDataState: OK
        execErrState: Alerting
        for: 0s
        labels:
          severity: critical
        annotations:
          summary: 5xx 에러가 발생했습니다.
          description: |
            - API 서버 ERROR 로그
            - 발생 API 및 예외 내용
            - DB 및 외부 연동 서비스 상태

      - uid: didit-http-5xx-rate-critical
        title: '[CRITICAL] 5xx 에러율 1% 초과'
        condition: C
        data:
          - refId: A
            datasourceUid: prometheus
            relativeTimeRange:
              from: 600
              to: 0
            model:
              refId: A
              expr: |
                sum(
                  rate(
                    http_server_requests_seconds_count{
                      environment="prod",
                      status=~"5.."
                    }[5m]
                  )
                )
                /
                sum(
                  rate(
                    http_server_requests_seconds_count{
                      environment="prod"
                    }[5m]
                  )
                )
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200

          - refId: B
            datasourceUid: __expr__
            model:
              refId: B
              type: reduce
              expression: A
              reducer: last
              datasource:
                type: __expr__
                uid: __expr__

          - refId: C
            datasourceUid: __expr__
            model:
              refId: C
              type: threshold
              expression: B
              conditions:
                - evaluator:
                    type: gt
                    params: [ 0.01 ]
                  operator:
                    type: and
                  query:
                    params: [ C ]
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__

        noDataState: OK
        execErrState: Alerting
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: 5xx 에러율이 1%를 초과했습니다.
          description: |
            - API 서버 로그
            - 최근 배포 여부
            - 특정 API 및 외부 서비스 장애 여부

      - uid: didit-hikaricp-usage-critical
        title: '[CRITICAL] HikariCP 커넥션 풀 사용률 90% 초과'
        condition: C
        data:
          - refId: A
            datasourceUid: prometheus
            relativeTimeRange:
              from: 300
              to: 0
            model:
              refId: A
              expr: |
                max(hikaricp_connections_active{environment="prod"})
                /
                max(hikaricp_connections_max{environment="prod"})
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200

          - refId: B
            datasourceUid: __expr__
            model:
              refId: B
              type: reduce
              expression: A
              reducer: last
              datasource:
                type: __expr__
                uid: __expr__

          - refId: C
            datasourceUid: __expr__
            model:
              refId: C
              type: threshold
              expression: B
              conditions:
                - evaluator:
                    type: gt
                    params: [ 0.9 ]
                  operator:
                    type: and
                  query:
                    params: [ C ]
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__

        noDataState: OK
        execErrState: Alerting
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: HikariCP 커넥션 풀 사용률이 90%를 초과했습니다.
          description: |
            - HikariCP Active / Idle 커넥션 상태
            - Slow API 및 DB 병목 여부
            - DB Slow Query 및 커넥션 누수 여부

  - orgId: 1
    name: didit-prod-warning
    folder: Didit Alerts
    interval: 1m
    rules:
      - uid: didit-gc-stw-warning
        title: GC Stop The World Warning
        condition: C
        data:
          - refId: A
            datasourceUid: prometheus
            relativeTimeRange:
              from: 300
              to: 0
            model:
              refId: A
              expr: |
                max(jvm_gc_pause_seconds_max{environment="prod"})
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200

          - refId: B
            datasourceUid: __expr__
            model:
              refId: B
              type: reduce
              expression: A
              reducer: last
              datasource:
                type: __expr__
                uid: __expr__

          - refId: C
            datasourceUid: __expr__
            model:
              refId: C
              type: threshold
              expression: B
              conditions:
                - evaluator:
                    type: gt
                    params: [ 1 ]
                  operator:
                    type: and
                  query:
                    params: [ C ]
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__

        noDataState: OK
        execErrState: Alerting
        for: 0s
        labels:
          severity: warning
        annotations:
          summary: JVM GC pause max is above 1 second
      - uid: didit-http-p99-latency-warning
        title: p99 Response Time Warning
        condition: C
        data:
          - refId: A
            datasourceUid: prometheus
            relativeTimeRange:
              from: 600
              to: 0
            model:
              refId: A
              expr: |
                histogram_quantile(
                  0.99,
                  sum(
                    rate(
                      http_server_requests_seconds_bucket{
                        environment="prod"
                      }[5m]
                    )
                  ) by (le)
                )
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200

          - refId: B
            datasourceUid: __expr__
            model:
              refId: B
              type: reduce
              expression: A
              reducer: last
              datasource:
                type: __expr__
                uid: __expr__

          - refId: C
            datasourceUid: __expr__
            model:
              refId: C
              type: threshold
              expression: B
              conditions:
                - evaluator:
                    type: gt
                    params: [ 2 ]
                  operator:
                    type: and
                  query:
                    params: [ C ]
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__

        noDataState: OK
        execErrState: Alerting
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: HTTP p99 response time is above 2 seconds

      - uid: didit-root-disk-usage-warning
        title: Root Disk Usage Warning
        condition: C
        data:
          - refId: A
            datasourceUid: prometheus
            relativeTimeRange:
              from: 600
              to: 0
            model:
              refId: A
              expr: |
                (
                  node_filesystem_size_bytes{
                    environment="prod",
                    mountpoint="/"
                  }
                  -
                  node_filesystem_free_bytes{
                    environment="prod",
                    mountpoint="/"
                  }
                )
                /
                node_filesystem_size_bytes{
                  environment="prod",
                  mountpoint="/"
                }
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200

          - refId: B
            datasourceUid: __expr__
            model:
              refId: B
              type: reduce
              expression: A
              reducer: max
              datasource:
                type: __expr__
                uid: __expr__

          - refId: C
            datasourceUid: __expr__
            model:
              refId: C
              type: threshold
              expression: B
              conditions:
                - evaluator:
                    type: gt
                    params: [ 0.8 ]
                  operator:
                    type: and
                  query:
                    params: [ C ]
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__

        noDataState: OK
        execErrState: Alerting
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Root disk usage is above 80%

      - uid: didit-os-memory-usage-warning
        title: OS Memory Usage Warning
        condition: C
        data:
          - refId: A
            datasourceUid: prometheus
            relativeTimeRange:
              from: 600
              to: 0
            model:
              refId: A
              expr: |
                1 - (
                  node_memory_MemAvailable_bytes{
                    environment="prod"
                  }
                  /
                  node_memory_MemTotal_bytes{
                    environment="prod"
                  }
                )
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200

          - refId: B
            datasourceUid: __expr__
            model:
              refId: B
              type: reduce
              expression: A
              reducer: last
              datasource:
                type: __expr__
                uid: __expr__

          - refId: C
            datasourceUid: __expr__
            model:
              refId: C
              type: threshold
              expression: B
              conditions:
                - evaluator:
                    type: gt
                    params: [ 0.9 ]
                  operator:
                    type: and
                  query:
                    params: [ C ]
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__

        noDataState: OK
        execErrState: Alerting
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: OS memory usage is above 90%