CREATE TABLE retrospective_attachments (
    id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    retrospective_id BINARY(16) NOT NULL,
    chat_message_id BINARY(16) DEFAULT NULL,
    storage_key VARCHAR(500) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    file_type VARCHAR(10) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    expected_size BIGINT NOT NULL,
    actual_size BIGINT DEFAULT NULL,
    upload_status VARCHAR(20) NOT NULL,
    analysis_status VARCHAR(30) NOT NULL,
    analysis_attempt_count INT NOT NULL DEFAULT 0,
    analysis_error_code VARCHAR(50) DEFAULT NULL,
    extracted_content MEDIUMTEXT DEFAULT NULL,
    contains_sensitive_data BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at DATETIME NOT NULL,
    uploaded_at DATETIME DEFAULT NULL,
    analyzed_at DATETIME DEFAULT NULL,
    deleted_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_attachment_retrospective
        FOREIGN KEY (retrospective_id) REFERENCES retrospectives(id) ON DELETE CASCADE,
    CONSTRAINT fk_attachment_message
        FOREIGN KEY (chat_message_id) REFERENCES chat_messages(id) ON DELETE CASCADE,
    CONSTRAINT uq_attachment_storage_key UNIQUE (storage_key),
    INDEX idx_attachment_owner (user_id, retrospective_id),
    INDEX idx_attachment_message (chat_message_id),
    INDEX idx_attachment_orphan_cleanup (chat_message_id, deleted_at, expires_at),
    INDEX idx_attachment_storage_cleanup (upload_status)
);
