package com.didit.application.audit

enum class AuditAction {
    USER_LOGGED_IN,
    USER_LOGGED_OUT,
    USER_SIGNED_UP,
    USER_PROFILE_UPDATED,
    USER_WITHDREW,

    ADMIN_LOGGED_IN,
    ADMIN_LOGGED_OUT,
    ADMIN_INVITED,
    ADMIN_APPROVED,
    ADMIN_REJECTED,
    ADMIN_DELETED,
    ADMIN_NOTICE_EMAIL_SENT,

    INQUIRY_ANSWERED,
    INQUIRY_ANSWER_UPDATED,
    INQUIRY_ANSWER_DELETED,
    INQUIRY_REGISTERED,
    INQUIRY_DELETED,

    NOTICE_REGISTERED,
    NOTICE_UPDATED,
    NOTICE_DELETED,

    RETROSPECTIVE_STARTED,
    RETROSPECTIVE_SAVED,
    RETROSPECTIVE_DELETED,
    RETROSPECTIVE_RESTARTED,

    BADGE_ACQUIRED,

    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,

    APP_CONFIG_UPDATED,

    USER_FORCE_WITHDREW,
    USER_MARKETING_CONSENT_UPDATED,

    ADMIN_NOTIFICATION_SENT,
}
